#!/bin/sh
nasm -f $3 $1 -o "${2}.o"
objcopy -O binary --only-section .text "${2}.o" "$2"
SIZE=$(du --apparent-size --block-size=1 $2 2>/dev/null | awk '{print $1}')
echo "Created payload $2 (${SIZE} bytes)"
